config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :chirps

  root 'chirps#index'

end

app/models/chirp.rb
class Chirp < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :chirps
	validates_presence_of :username
	validates_uniqueness_of :username
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
  	devise_parameter_sanitizer.for
end

app/controllers/chirps_controller.rb
class ChirpsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show] 
  before_action :set_chirp, only: [:show, :edit, :update, :destroy]

  # GET /chirps
  def index
    # instance variable - means that this is data associated with this controller instance
    # at sign is v important b/c of this!!!
    @chirps = Chirp.all 
  end

  # GET /chirps/1
  def show
  end

  # GET /chirps/new
  def new
    @chirp = Chirp.new
  end

  # GET /chirps/1/edit
  def edit
  end

  # POST /chirps
  def create
    @chirp = Chirp.new(chirp_params)

    if @chirp.save
      redirect_to @chirp, notice: 'Chirp was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /chirps/1
  def update
    if @chirp.update(chirp_params)
      redirect_to @chirp, notice: 'Chirp was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /chirps/1
  def destroy
    @chirp.destroy
    redirect_to chirps_url, notice: 'Chirp was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chirp
      @chirp = Chirp.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def chirp_params
      params.require(:chirp).permit(:body, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chirps_helper.rb
module ChirpsHelper
end

app/views/chirps/_form.html.erb
<!--This file is called a partial
    Instead of duplicating it, we call this in different routes
-->

<%= form_for(@chirp) do |f| %>
  <% if @chirp.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chirp.errors.count, "error") %> prohibited this chirp from being saved:</h2>

      <ul>
      <% @chirp.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/chirps/edit.html.erb
<h1>Editing Chirp</h1>

<%= render 'form' %>

<%= link_to 'Show', @chirp %> |
<%= link_to 'Back', chirps_path %>

app/views/chirps/index.html.erb
<p id="notice"><%= notice %></p>

<% if user_signed_in? %>
  <p>Hello, <%= current_user.email %></p>
<% end %>

<h1>Listing Chirps</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @chirps.each do |chirp| %>
      <tr>
        <td><%= chirp.body %></td>
        <td><%= chirp.user_id %></td>
        <!--link_to: creates a link
            first argument is the label
            second is the path -->
        <td><%= link_to 'Show', chirp %></td>
        <td><%= link_to 'Edit', edit_chirp_path(chirp) %></td>
        <td><%= link_to 'Destroy', chirp, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Chirp', new_chirp_path %>

app/views/chirps/new.html.erb
<h1>New Chirp</h1>

<%= render 'form' %>

<%= link_to 'Back', chirps_path %>

app/views/chirps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @chirp.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @chirp.user_id %>
</p>

<%= link_to 'Edit', edit_chirp_path(@chirp) %> |
<%= link_to 'Back', chirps_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tweeter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>